YOUTUBE_URL="ESTA ES LA API"
CHARTS_DIRECTORY = "my_youtube/charts/"
VIDEOS_DIRECTORY = "my_youtube/videos/"
JUANBAFUENTES_URL = "https://github.com/juanbafuentes"
REPO_URL = "https://github.com/juanbafuentes/my_youtube"